configuration: Release

# restore NuGet packages before running MSBuild
before_build:
  - nuget restore
  
# package Web Application project for Web Deploy
build:
  verbosity: minimal
  publish_wap: true
  
# Build 
version: 1.0.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
artifacts:
- path: ./Build/*.nupkg
  name: NuGet
